backend:
  name: github
  repo: kiooo808/kiooo808.github.io
  branch: main
  site_domain: kiooo808.github.io

# 报错就是因为之前没读到下面这几行
media_folder: "source/images" 
public_folder: "/images"

collections:
  - name: "moments"
    label: "动态板块"
    label_singular: "动态"
    folder: "source/_posts"
    create: true
    slug: "moment-{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string", default: "日常碎碎念" }
      - { label: "发布时间", name: "date", widget: "datetime" }
      - { label: "布局样式", name: "layout", widget: "hidden", default: "essay" }
      - { label: "分类", name: "categories", widget: "hidden", default: "动态" }
      - { label: "动态内容", name: "body", widget: "markdown" }
